In [1]:
# imprt the dependencies
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [2]:
# create a set of random latitudes and longitudes combinations
lats =np.random.uniform(low=-90.000, high=90.000, size=1500)
lngs =np.random.uniform(low=-180.00, high=1800, size=1500)
lats_lngs = zip(lats, lngs)

In [3]:
coordinates = list(lats_lngs)

In [4]:
# Get the nearest city using the citipy module
from citipy import citipy

In [5]:
cities = [] # stores city names
for coordinate in coordinates:
    city = citipy.nearest_city(coordinate[0], coordinate[1]).city_name
    if city not in cities:
        cities.append(city)
len(cities)

198

In [6]:
# Perform an API call with the OpenWeatherMap
import requests
from config import weather_api_key

In [7]:
# Starting URL for Weather Map API Call.
url = "http://api.openweathermap.org/data/2.5/weather?units=Imperial&APPID=" + weather_api_key
print(url)

http://api.openweathermap.org/data/2.5/weather?units=Imperial&APPID=98e7bcbbdfd9e516604879f5d2a923ea

In [8]:
# Create an endpoint URL for a city.
city_url = url 
print(city_url)

http://api.openweathermap.org/data/2.5/weather?units=Imperial&APPID=98e7bcbbdfd9e516604879f5d2a923ea

In [9]:
# Make a 'Get' request for the city weather.
city_weather = requests.get(city_url)
city_weather.status_code

400

In [10]:
# Import the datetime module from the datetime library.
from datetime import datetime

In [52]:
city_data = []
# Print the beginning of the logging.
print("Beginning Data Retrieval     ")
print("-----------------------------")

# Create counters.
record_count = 1
set_count = 1

# Loop through all the cities in the list.
for i, city in enumerate(cities):

   
    if (i % 50 == 0 and i >= 50):
        set_count += 1
        record_count = 1
   
    city_url = url + "&q=" + city
    print(f"Processing Record {record_count} of Set {set_count} | {city}")
    record_count += 1

    
    
    try:
        
        city_weather = requests.get(city_url).json()
        
        
        
        city_lat = city_weather["coord"]["lat"]
        city_country = city_weather["sys"]["country"]
        city_lng = city_weather["coord"]["lon"]
        city_max_temp = city_weather["main"]["temp_max"]
        city_humidity = city_weather["main"]["humidity"]
        city_clouds = city_weather["clouds"]["all"]
        city_wind = city_weather["wind"]["speed"]
        weather_description = city_weather["weather"][0]["description"]
        
        try:
            rain_inches = city_weather["rain"]["3h"]
        except:
            rain_inches = ("0")
            pass
        try:
            snow_inches = city_weather["snow"]["3h"]
        except:
            snow_inches = ("0")  
            pass
               
        
               
        # Convert the date to ISO standard.
        city_date = datetime.utcfromtimestamp(city_weather["dt"]).strftime('%Y-%m-%d %H:%M:%S')
        # Append the city information into city_data list.
        city_data.append({"City": city.title(),
                          
                          
                          "Country": city_country,
                          "Date": city_date,
                          "Lat": city_lat,
                          "Lng": city_lng,
                          "Max Temp": city_max_temp,
                          "Humidity": city_humidity,
                          "Cloudiness": city_clouds,
                          "Wind Speed": city_wind,
                          "Current Description": weather_description,
                          "Rain inches (last 3hours)": rain_inches,
                          "Snow inches(last 3hours)": snow_inches})
                                                                            
                          

# If an error is experienced, skip the city.
    except:
        print("City not found. Skipping...")
        pass

# Indicate that Data Loading is complete.
print("-----------------------------")
print("Data Retrieval Complete      ")
print("-----------------------------")

Beginning Data Retrieval
-----------------------------
Processing Record 1 of Set 1 | beringovskiy
Processing Record 2 of Set 1 | ruatoria
City not found. Skipping...
Processing Record 3 of Set 1 | asau
Processing Record 4 of Set 1 | tolaga bay
Processing Record 5 of Set 1 | taolanaro
City not found. Skipping...
Processing Record 6 of Set 1 | hermanus
Processing Record 7 of Set 1 | albany
Processing Record 8 of Set 1 | severo-kurilsk
Processing Record 9 of Set 1 | atuona
Processing Record 10 of Set 1 | cairns
Processing Record 11 of Set 1 | jequie
Processing Record 12 of Set 1 | dikson
Processing Record 13 of Set 1 | provideniya
Processing Record 14 of Set 1 | rungata
City not found. Skipping...
Processing Record 15 of Set 1 | airai
Processing Record 16 of Set 1 | cervo
Processing Record 17 of Set 1 | djambala
Processing Record 18 of Set 1 | port macquarie
Processing Record 19 of Set 1 | iqaluit
Processing Record 20 of Set 1 | puerto ayora
Processing Record 21 of Set 1 | busselton
Processing Record 22 of Set 1 | hobart
Processing Record 23 of Set 1 | leningradskiy
Processing Record 24 of Set 1 | georgetown
Processing Record 25 of Set 1 | muisne
Processing Record 26 of Set 1 | kodiak
Processing Record 27 of Set 1 | guspini
Processing Record 28 of Set 1 | wanning
Processing Record 29 of Set 1 | sioux lookout
Processing Record 30 of Set 1 | navrongo
Processing Record 31 of Set 1 | fengkou
Processing Record 32 of Set 1 | vaini
Processing Record 33 of Set 1 | kenai
Processing Record 34 of Set 1 | mataura
Processing Record 35 of Set 1 | tiksi
Processing Record 36 of Set 1 | vao
Processing Record 37 of Set 1 | murgab
Processing Record 38 of Set 1 | rikitea
Processing Record 39 of Set 1 | sibolga
Processing Record 40 of Set 1 | bambous virieux
Processing Record 41 of Set 1 | chuy
Processing Record 42 of Set 1 | kahului
Processing Record 43 of Set 1 | vammala
Processing Record 44 of Set 1 | pevek
Processing Record 45 of Set 1 | grahamstown
Processing Record 46 of Set 1 | jamestown
Processing Record 47 of Set 1 | concepcion
Processing Record 48 of Set 1 | chokurdakh
Processing Record 49 of Set 1 | bluff
Processing Record 50 of Set 1 | attawapiskat
City not found. Skipping...
Processing Record 1 of Set 2 | ushuaia
Processing Record 2 of Set 2 | norman wells
Processing Record 3 of Set 2 | hilo
Processing Record 4 of Set 2 | yanam
Processing Record 5 of Set 2 | cape town
Processing Record 6 of Set 2 | portage
Processing Record 7 of Set 2 | port blair
Processing Record 8 of Set 2 | avarua
Processing Record 9 of Set 2 | salalah
Processing Record 10 of Set 2 | bowen
Processing Record 11 of Set 2 | esperance
Processing Record 12 of Set 2 | stonewall
Processing Record 13 of Set 2 | juneau
Processing Record 14 of Set 2 | barentsburg
City not found. Skipping...
Processing Record 15 of Set 2 | linxia
Processing Record 16 of Set 2 | kaitangata
Processing Record 17 of Set 2 | cherskiy
Processing Record 18 of Set 2 | derzhavinsk
Processing Record 19 of Set 2 | garden city
Processing Record 20 of Set 2 | khonuu
City not found. Skipping...
Processing Record 21 of Set 2 | victoria
Processing Record 22 of Set 2 | fare
Processing Record 23 of Set 2 | sur
Processing Record 24 of Set 2 | nuuk
Processing Record 25 of Set 2 | sanchez
Processing Record 26 of Set 2 | barrow
Processing Record 27 of Set 2 | dumas
Processing Record 28 of Set 2 | ushtobe
Processing Record 29 of Set 2 | san julian
Processing Record 30 of Set 2 | erenhot
Processing Record 31 of Set 2 | klaksvik
Processing Record 32 of Set 2 | kapaa
Processing Record 33 of Set 2 | new norfolk
Processing Record 34 of Set 2 | scalloway
City not found. Skipping...
Processing Record 35 of Set 2 | ucluelet
Processing Record 36 of Set 2 | punta arenas
Processing Record 37 of Set 2 | masuguru
Processing Record 38 of Set 2 | dunedin
Processing Record 39 of Set 2 | ayan
Processing Record 40 of Set 2 | saint-philippe
Processing Record 41 of Set 2 | groditz
City not found. Skipping...
Processing Record 42 of Set 2 | gazojak
Processing Record 43 of Set 2 | chetumal
Processing Record 44 of Set 2 | waipawa
Processing Record 45 of Set 2 | cabo san lucas
Processing Record 46 of Set 2 | dingle
Processing Record 47 of Set 2 | viedma
Processing Record 48 of Set 2 | saldanha
Processing Record 49 of Set 2 | kerteh
City not found. Skipping...
Processing Record 50 of Set 2 | saint george
Processing Record 1 of Set 3 | benguela
Processing Record 2 of Set 3 | bratsk
Processing Record 3 of Set 3 | palmer
Processing Record 4 of Set 3 | adra
Processing Record 5 of Set 3 | bredasdorp
Processing Record 6 of Set 3 | bolshoye soldatskoye
City not found. Skipping...
Processing Record 7 of Set 3 | taoudenni
Processing Record 8 of Set 3 | pangnirtung
Processing Record 9 of Set 3 | manoel urbano
Processing Record 10 of Set 3 | butaritari
Processing Record 11 of Set 3 | luderitz
Processing Record 12 of Set 3 | pascagoula
Processing Record 13 of Set 3 | sambava
Processing Record 14 of Set 3 | buala
Processing Record 15 of Set 3 | srednekolymsk
Processing Record 16 of Set 3 | sijunjung
Processing Record 17 of Set 3 | touros
Processing Record 18 of Set 3 | dzilam gonzalez
Processing Record 19 of Set 3 | matagami
Processing Record 20 of Set 3 | richards bay
Processing Record 21 of Set 3 | isangel
Processing Record 22 of Set 3 | jiazi
Processing Record 23 of Set 3 | tazovskiy
Processing Record 24 of Set 3 | talnakh
Processing Record 25 of Set 3 | comodoro rivadavia
Processing Record 26 of Set 3 | thompson
Processing Record 27 of Set 3 | heze
Processing Record 28 of Set 3 | nouadhibou
Processing Record 29 of Set 3 | saskylakh
Processing Record 30 of Set 3 | sao filipe
Processing Record 31 of Set 3 | port lincoln
Processing Record 32 of Set 3 | bac lieu
Processing Record 33 of Set 3 | rorvik
Processing Record 34 of Set 3 | san patricio
Processing Record 35 of Set 3 | tasiilaq
Processing Record 36 of Set 3 | leshukonskoye
Processing Record 37 of Set 3 | ribeira grande
Processing Record 38 of Set 3 | majene
Processing Record 39 of Set 3 | tarutyne
Processing Record 40 of Set 3 | yaroslavl
Processing Record 41 of Set 3 | marawi
Processing Record 42 of Set 3 | constitucion
Processing Record 43 of Set 3 | mar del plata
Processing Record 44 of Set 3 | linqing
Processing Record 45 of Set 3 | gryazovets
Processing Record 46 of Set 3 | solnechnyy
Processing Record 47 of Set 3 | qaanaaq
Processing Record 48 of Set 3 | bintulu
Processing Record 49 of Set 3 | laguna
Processing Record 50 of Set 3 | goderich
Processing Record 1 of Set 4 | arlit
Processing Record 2 of Set 4 | xiangdong
City not found. Skipping...
Processing Record 3 of Set 4 | formoso do araguaia
City not found. Skipping...
Processing Record 4 of Set 4 | auki
Processing Record 5 of Set 4 | carnarvon
Processing Record 6 of Set 4 | ivanava
Processing Record 7 of Set 4 | beboto
Processing Record 8 of Set 4 | ahipara
Processing Record 9 of Set 4 | la reforma
Processing Record 10 of Set 4 | torbay
Processing Record 11 of Set 4 | sosnogorsk
Processing Record 12 of Set 4 | tumannyy
City not found. Skipping...
Processing Record 13 of Set 4 | los llanos de aridane
Processing Record 14 of Set 4 | klyuchi
Processing Record 15 of Set 4 | parabel
Processing Record 16 of Set 4 | grand-santi
Processing Record 17 of Set 4 | qeshm
Processing Record 18 of Set 4 | lompoc
Processing Record 19 of Set 4 | nikolskoye
Processing Record 20 of Set 4 | kayanga
Processing Record 21 of Set 4 | ponta do sol
Processing Record 22 of Set 4 | iranshahr
Processing Record 23 of Set 4 | bosaso
Processing Record 24 of Set 4 | shahrud
Processing Record 25 of Set 4 | arraial do cabo
Processing Record 26 of Set 4 | tuktoyaktuk
Processing Record 27 of Set 4 | ozinki
Processing Record 28 of Set 4 | rincon
Processing Record 29 of Set 4 | isla mujeres
Processing Record 30 of Set 4 | walvis bay
Processing Record 31 of Set 4 | byron bay
Processing Record 32 of Set 4 | ekimchan
Processing Record 33 of Set 4 | port alfred
Processing Record 34 of Set 4 | castro
Processing Record 35 of Set 4 | palabuhanratu
City not found. Skipping...
Processing Record 36 of Set 4 | tawnat
City not found. Skipping...
Processing Record 37 of Set 4 | acarau
Processing Record 38 of Set 4 | bubaque
Processing Record 39 of Set 4 | shahada
Processing Record 40 of Set 4 | ambovombe
Processing Record 41 of Set 4 | yellowknife
Processing Record 42 of Set 4 | nguiu
City not found. Skipping...
Processing Record 43 of Set 4 | bukama
Processing Record 44 of Set 4 | mahebourg
Processing Record 45 of Set 4 | arman
Processing Record 46 of Set 4 | port hedland
Processing Record 47 of Set 4 | maloshuyka
City not found. Skipping...
Processing Record 48 of Set 4 | puerto montt
-----------------------------
Data Retrieval Complete
-----------------------------

In [53]:
# Convert the array of dictionaries to a Pandas DataFrame.
city_data_df = pd.DataFrame(city_data)
city_data_df.head(10)

,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description,Rain inches (last 3hours),Snow inches(last 3hours)
0,Beringovskiy,RU,2020-04-02 13:28:22,63.05,179.32,27.07,98,86,9.28,light snow,0,0.49
1,Asau,RO,2020-04-02 13:28:22,46.43,26.40,55.00,27,4,10.29,clear sky,0,0
2,Tolaga Bay,NZ,2020-04-02 13:28:22,-38.37,178.30,57.90,83,57,15.14,light rain,0.25,0
3,Hermanus,ZA,2020-04-02 13:28:23,-34.42,19.23,87.01,42,0,8.99,clear sky,0,0
4,Albany,US,2020-04-02 13:25:22,42.60,-73.97,43.00,60,75,6.93,broken clouds,0,0
5,Severo-Kurilsk,RU,2020-04-02 13:28:23,50.68,156.12,33.22,93,100,18.72,light snow,0,0.47
6,Atuona,PF,2020-04-02 13:28:23,-9.80,-139.03,81.59,78,17,11.92,light rain,0.52,0
7,Cairns,AU,2020-04-02 13:28:02,-16.92,145.77,77.00,78,72,4.70,broken clouds,0,0
8,Jequie,BR,2020-04-02 13:28:24,-13.86,-40.08,81.16,66,60,2.04,light rain,0.22,0
9,Dikson,RU,2020-04-02 13:28:24,73.51,80.55,9.19,91,100,24.02,overcast clouds,0,0

In [42]:
city_data_df.to_csv("Resources/Weather_challenge.csv")

In [87]:
city_data_df

,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description,Rain inches (last 3hours),Snow inches(last 3hours)
0,Beringovskiy,RU,2020-04-02 13:28:22,63.05,179.32,27.07,98,86,9.28,light snow,0,0.49
1,Asau,RO,2020-04-02 13:28:22,46.43,26.40,55.00,27,4,10.29,clear sky,0,0
2,Tolaga Bay,NZ,2020-04-02 13:28:22,-38.37,178.30,57.90,83,57,15.14,light rain,0.25,0
3,Hermanus,ZA,2020-04-02 13:28:23,-34.42,19.23,87.01,42,0,8.99,clear sky,0,0
4,Albany,US,2020-04-02 13:25:22,42.60,-73.97,43.00,60,75,6.93,broken clouds,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
176,Bukama,CD,2020-04-02 13:28:48,-9.20,25.85,86.34,60,69,2.01,moderate rain,3.96,0
177,Mahebourg,MU,2020-04-02 13:24:59,-20.41,57.70,82.40,78,40,6.93,shower rain,0,0
178,Arman,RU,2020-04-02 13:28:48,59.70,150.17,16.90,93,6,4.32,clear sky,0,0
179,Port Hedland,AU,2020-04-02 13:28:48,-20.32,118.57,80.60,69,56,8.05,broken clouds,0,0
180,Puerto Montt,CL,2020-04-02 13:28:49,-41.47,-72.94,46.40,100,40,2.24,mist,0,0

In [88]:
# output file
city_data_df.to_csv("Resources/WeatherPy_challenge.csv")

In [ ]:
#  Answer this question using Pandas methods: How many cities have recorded rainfall or snow?

In [67]:
city_data_df.columns

Index(['City', 'Country', 'Date', 'Lat', 'Lng', 'Max Temp', 'Humidity',
       'Cloudiness', 'Wind Speed', 'Current Description',
       'Rain inches (last 3hours)', 'Snow inches(last 3hours)'],
      dtype='object')

In [83]:

sum(city_data_df['Rain inches (last 3hours)'] !='0')

23

In [85]:
sum(city_data_df['Snow inches(last 3hours)'] !='0')

9